# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp',
            name='address',
        ),
        migrations.RemoveField(
            model_name='corp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='corp',
            name='tel',
        ),
        migrations.AddField(
            model_name='corp',
            name='user_ceo_name',
            field=models.CharField(max_length=20, null=True, verbose_name='\u4ee3\u8868\u53d6\u7de0\u5f79'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_email',
            field=models.EmailField(max_length=256, null=True, verbose_name='E-mail \u30a2\u30c9\u30ec\u30b9'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_employee_num',
            field=models.CharField(max_length=7, null=True, verbose_name='\u5f93\u696d\u54e1\u6570'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_img',
            field=models.ImageField(null=True, upload_to=None, verbose_name='\u4f1a\u793e\u30a2\u30a4\u30b3\u30f3'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_last_logined_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u7d42\u30ed\u30b0\u30a4\u30f3\u65e5\u6642'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_login_times',
            field=models.IntegerField(null=True, verbose_name='\u30ed\u30b0\u30a4\u30f3\u56de\u6570'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_name',
            field=models.CharField(max_length=150, null=True, verbose_name='\u4f1a\u793e\u540d'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_password',
            field=models.CharField(max_length=8, null=True, verbose_name='\u30d1\u30b9\u30ef\u30fc\u30c9'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_register_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u767b\u9332\u65e5\u6642'),
        ),
        migrations.AddField(
            model_name='corp',
            name='user_tel',
            field=models.CharField(max_length=11, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7'),
        ),
    ]
